#主配置文件

spring:
  redis:
    host: 106.52.218.164
    port: 6379
    password: 20020109.Zhh
  #配置MVC视图后缀
  mvc:
    view:
      suffix: ".html"



  main:
    allow-bean-definition-overriding: true

  datasource:
    username: root
    password: 20020109.Zhh
    url: jdbc:mysql://localhost:3306/login?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

#    连接池配置
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000



